### ISSUE TITLE
Problem with version 2.6 with Anaconda 3 21.05 on Windows

### ISSUE THREAD

**Issue by toncho11** [pyRiemann/pyRiemann#126]
Hi,

I did install it with 
`pip install pyriemann`
But it gives me this error: 
`ImportError: cannot import name '_init_centroids' from 'sklearn.cluster._kmeans`

So one needs to fix this or download the code for pyriemann 2.7dev and replace it in Anaconda. 
pip install pyriemann from github does not work good because it can mess up with versions of the existing libraries.

So I think you need to release version 2.7 to the public.

**Comment by agramfort** [comment]
I push for testing in https://test.pypi.org/project/pyriemann/

can you try if it works for you?

if so I'll push one release to pypi

**Comment by toncho11** [comment]
You did not change the version. It still says 2.6 and thus it does not want to install. Please update.

**Comment by agramfort** [comment]
did you try to run

pip install -i https://test.pypi.org/simple/ pyriemann

?

>

**Comment by toncho11** [comment]
yes, it says already installed.

But here https://test.pypi.org/project/pyriemann/ it says pypi package 2,6

**Comment by agramfort** [comment]
don't look at the badge

can you do:

pip install -U -i https://test.pypi.org/simple/ pyriemann

**Comment by toncho11** [comment]
How it gives another thing:

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"\\Local\\Temp\\pip-install-6dp0u7ei\\pyriemann_2679cd1d615b4c51adc63480f01d4229\\setup.py'"'"'; __file__='"'"'C:\\Users\\AppData\\Local\\Temp\\pip-install-6dp0u7ei\\pyriemann_2679cd1d615b4c51adc63480f01d4229\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AppData\Local\Temp\pip-pip-egg-info-56tbqbub'
         cwd: C:\Users\AppData\Local\Temp\pip-install-6dp0u7ei\pyriemann_2679cd1d615b4c51adc63480f01d4229\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AppData\Local\Temp\pip-install-6dp0u7ei\pyriemann_2679cd1d615b4c51adc63480f01d4229\setup.py", line 17, in <module>
        long_description = fid.read()
      File "C:\Anaconda\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4325: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding https://test-files.pythonhosted.org/packages/50/11/5f530fe7d865d96a9939ad55c6cb4710ed23955395bcdbc877b6ef7024e3/pyriemann-0.2.7rc0.tar.gz#sha256=d8150b99c7f419ebbdc846a3e8e86426d9b197a5fc20a84a041345d66a5e4f11 (from https://test.pypi.org/simple/pyriemann/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Requirement already satisfied: scikit-learn in c:\andreevi\anaconda\lib\site-packages (from pyriemann) (0.24.1)
Requirement already satisfied: pandas in c:\andreevi\anaconda\lib\site-packages (from pyriemann) (1.2.4)
Requirement already satisfied: scipy in c:\andreevi\anaconda\lib\site-packages (from pyriemann) (1.6.2)
Requirement already satisfied: numpy in c:\andreevi\anaconda\lib\site-packages (from pyriemann) (1.20.1)
Requirement already satisfied: joblib in c:\andreevi\anaconda\lib\site-packages (from pyriemann) (1.0.1)
Requirement already satisfied: pytz>=2017.3 in c:\andreevi\anaconda\lib\site-packages (from pandas->pyriemann) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\anaconda\lib\site-packages (from pandas->pyriemann) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\anaconda\lib\site-packages (from python-dateutil>=2.7.3->pandas->pyriemann) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda\lib\site-packages (from scikit-learn->pyriemann) (2.1.0)
```

**Comment by agramfort** [comment]
can you try again now?

>

**Comment by toncho11** [comment]
Yes. it works.

**Comment by agramfort** [comment]
you're welcome ...
