### ISSUE TITLE
Error in fitting ElectrodeSelection class

### ISSUE THREAD

**Issue by vpKumaravel** [pyRiemann/pyRiemann#165]
Hello!

I have a covariance matrix of shape (1, 18, 18) - 1 trial, 18 channels.
I wanted to select channels based on the covariance matrix.

clf2 = ElectrodeSelection(nelec=2, metric='riemann', n_jobs=1)
fit_ = clf2.fit(cov1)

I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/site-packages/pyriemann/channelselection.py", line 83, in fit
    mdm.fit(X, y, sample_weight=sample_weight)
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/site-packages/pyriemann/classification.py", line 119, in fit
    self.covmeans_ = Parallel(n_jobs=self.n_jobs)(
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/vkumarav/anaconda3/envs/HDEnv/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: too many values to unpack (expected 3)

It seems that ElectrodeSelection fit does not require y, but MDM fit which is called within the block requires "y".
https://github.com/pyRiemann/pyRiemann/blob/0b6ed12845b9901be92b2a992cec34f38903dbba/pyriemann/channelselection.py#L83

Would appreciate any feedback on this issue, thank you so much!

Velu

**Comment by qbarthelemy** [comment]
Solved with  #166.
